### PR TITLE
Chinese translation

### PR DESCRIPTION
**Pull request by vmlinz**
I love this Android audit list of questions. I translated it into Chinese, please merge it.

### CODE REVIEW

**Comment by gragera** [comment]
Hi @vmlinz !

Thank you so much for the contribution :) . Would you mind to remove the English version from the file and just keep the Chinese version?

Cheers,

**Comment by vmlinz** [comment]
@gragera I will remove them when some issues got fixed. I asked some friends to help review it.

Thanks for the great list.

👍

**Comment by vmlinz** [comment]
@gragera English statements deleted. Please help merge it :)

**Comment by davideme** [comment]
👍

**Comment by pedrovgs** [comment]
Thank you so much @vmlinz :)

**Pull request merged**
