### PR TITLE
Add support to PT (portuguese) language

### PR DESCRIPTION
**Pull request by tiagobarreto**

### CODE REVIEW

**Comment by tiagobarreto** [comment]
@raphaeljlps @naldomadeira if you have a moment, could you review document?

**Comment by tiagobarreto** [comment]
@pedrovgs Revised document without comments.

**Comment by pedrovgs** [comment]
Sorry for the delay @tiagobarreto. A friend of mine has been reviewing the translation :) As the translation seems to be correct I'm merging this PR.

**Comment by tiagobarreto** [comment]
@pedrovgs no problem, @pedrovgs. thanks ;)

**Pull request merged**
